version: '3.8'

services:
  e2ee-messenger-bot:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: e2ee-messenger-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
    environment:
      - DOCKER_CONTAINER=true
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD", "python", "-c", "print('healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
