version: '3.8'

services:
  e2ee-messenger-bot:
    build: .
    container_name: e2ee-messenger-bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data:rw
    environment:
      - DOCKER_CONTAINER=true
      - PYTHONUNBUFFERED=1
    stdin_open: true
    tty: true
